language: php
sudo: false
cache: {directories: [$HOME/.composer]}
env: {global: [COMPOSER_FLAGS="--no-interaction --prefer-stable"]}
before_install:
  - phpenv config-rm xdebug.ini || return 0
  - composer global show hirak/prestissimo -q || travis_retry composer global require $COMPOSER_FLAGS hirak/prestissimo
jobs:
  include:
    - &STANDARD_TEST_JOB
      php: 5.6
      stage: PHP5
      install:
        - travis_retry composer update $COMPOSER_FLAGS
        - travis_retry composer require zendframework/zend-servicemanager:^$ZF $COMPOSER_FLAGS
        - composer info -D | sort
      script:
        - vendor/bin/phpunit || travis_terminate 1
        - php vendor/bin/php-cs-fixer --diff --dry-run -v fix
      env: ZF=2.0

    - <<: *STANDARD_TEST_JOB
      php: 5.6

    - <<: *STANDARD_TEST_JOB
      stage: PHP7
      php: 7.1
      env: ZF=3.0

    - <<: *STANDARD_TEST_JOB
      stage: PHP7
      php: 7.1
      env: ZF=3.0

  allow_failures:
    - php: nightly
