language: php
sudo: false
cache: {directories: [$HOME/.composer]}
env: {global: [COMPOSER_FLAGS="--no-interaction --prefer-stable"]}
jobs:
  include:
    - &STANDARD_TEST_JOB
      php: 5.6
      install:
        - travis_retry composer update $COMPOSER_FLAGS
        - travis_retry composer require zendframework/zend-servicemanager:^$ZF $COMPOSER_FLAGS
        - composer info -D | sort
      script:
        - vendor/bin/phpunit || travis_terminate 1
        - php vendor/bin/php-cs-fixer --diff --dry-run -v fix || travis_terminate 1
      env: ZF=2.0

    - <<: *STANDARD_TEST_JOB
      env: ZF=3.0

    - <<: *STANDARD_TEST_JOB
      php: 7.1
      env: ZF=2.0

    - <<: *STANDARD_TEST_JOB
      php: 7.1
      env: ZF=3.0
      after_success:
        - travis_retry php vendor/bin/php-coveralls --verbose

  allow_failures:
    - php: nightly
